//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinefilo_1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTORES
    {
        public ACTORES()
        {
            this.PAPEL = new HashSet<PAPEL>();
        }
    
        public string dni { get; set; }
        public string nombre { get; set; }
        public Nullable<int> edad { get; set; }
        public string sexo { get; set; }
    
        public virtual ICollection<PAPEL> PAPEL { get; set; }
    }
}
