//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinefilo_1.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cinefiloEntities : DbContext
    {
        public cinefiloEntities()
            : base("name=cinefiloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTORES> ACTORES { get; set; }
        public virtual DbSet<PAPEL> PAPEL { get; set; }
        public virtual DbSet<PELICULAS> PELICULAS { get; set; }
        public virtual DbSet<TEMAS> TEMAS { get; set; }
        public virtual DbSet<TIPOS_PAPEL> TIPOS_PAPEL { get; set; }
    }
}
