//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinefilo_1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAPEL
    {
        public string dni { get; set; }
        public int id_pelicula { get; set; }
        public int id_tipo_papel { get; set; }
    
        public virtual ACTORES ACTORES { get; set; }
        public virtual PELICULAS PELICULAS { get; set; }
        public virtual TIPOS_PAPEL TIPOS_PAPEL { get; set; }
    }
}
