//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinefilo_1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PELICULAS
    {
        public PELICULAS()
        {
            this.PAPEL = new HashSet<PAPEL>();
            this.TEMAS = new HashSet<TEMAS>();
        }
    
        public int id_pelicula { get; set; }
        public string titulo { get; set; }
        public string director { get; set; }
    
        public virtual ICollection<PAPEL> PAPEL { get; set; }
        public virtual ICollection<TEMAS> TEMAS { get; set; }
    }
}
