//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinefilo_1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMAS
    {
        public TEMAS()
        {
            this.PELICULAS = new HashSet<PELICULAS>();
        }
    
        public int id_tema { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<PELICULAS> PELICULAS { get; set; }
    }
}
