//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinefilo_1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOS_PAPEL
    {
        public TIPOS_PAPEL()
        {
            this.PAPEL = new HashSet<PAPEL>();
        }
    
        public int id_tipos { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<PAPEL> PAPEL { get; set; }
    }
}
